ConnectRefuseError: removed the proxy from properties.gradle file to allow downloading of build tools during CI. (#5434)
* NearbyParentFragment : added referer

In file NearbyParentFragment.java, I added header property, i.e., the referer - http://maps.wikimedia.org/
and set tile source to wikimedia.

* Reworded comments

* sdkmanager: added installation command for build-tools-30.0.3

* Revert "sdkmanager: added installation command for build-tools-30.0.3"

This reverts commit b3e5019e36e50d8e94f9f0970222988fe75ade3b.

* Update android.yml

* Update gradle.properties

* android.yml: removed extra debug commands

Removed some debug commands because they are no longer needed.

---------

Co-authored-by: Nicolas Raoul <nicolas.raoul@gmail.com>